# Generated by Django 5.0.2 on 2024-02-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Pictures',
        ),
    ]
