# Generated by Django 5.0.2 on 2024-02-21 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_project_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 2, 21, 7, 422988, tzinfo=datetime.timezone.utc)),
        ),
    ]
