# Generated by Django 5.0.2 on 2024-02-21 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_pictures_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
