# Generated by Django 5.0.2 on 2024-02-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_pictures_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(max_length=250)),
                ('musician_name', models.CharField(max_length=100)),
                ('release_year', models.PositiveIntegerField()),
                ('track', models.FileField(upload_to='album/')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=250)),
                ('release_year', models.PositiveIntegerField()),
                ('video', models.FileField(upload_to='videos/')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.genre')),
            ],
        ),
    ]
