# Generated by Django 5.0.2 on 2024-02-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_genre_track_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.FileField(upload_to='album/%y'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/%y'),
        ),
    ]
